"""
Common Utilities Module for the advanced translation pipeline.

This module will house:
- Genuinely reusable utility functions (e.g., decorators, file helpers if any).
- The Gemini API client wrapper.
"""

# Placeholder for imports (e.g., google.generativeai for Gemini SDK)
# import google.generativeai as genai
import json # Import the json module

class GeminiClient:
    def __init__(self, api_key: str, client_config: dict = None):
        """
        Initializes the Gemini API client.

        Args:
            api_key (str): The API key for accessing Gemini.
            client_config (dict, optional): Additional configuration for the Gemini client
                                            (e.g., model name to use by default, safety settings).
        """
        if not api_key:
            raise ValueError("API key must be provided for GeminiClient.")
        
        self.api_key = api_key
        self.client_config = client_config or {}
        
        # Configure the Gemini client (actual SDK call)
        # genai.configure(api_key=self.api_key)
        
        # Initialize the model - this might be done per call or once if using a default
        # self.model = genai.GenerativeModel(
        #    self.client_config.get("model_name", "gemini-pro")
        # )
        
        print(f"GeminiClient initialized. Config: {self.client_config}")
        print(f"GeminiClient: API key {'provided' if api_key else 'NOT PROVIDED'}.")


    def generate_content(self, prompt: str, generation_config=None, safety_settings=None) -> str:
        """
        Generates content using the Gemini API.

        Args:
            prompt (str): The prompt to send to Gemini.
            generation_config (genai.types.GenerationConfig, optional): Configuration for generation.
            safety_settings (list of genai.types.SafetySetting, optional): Safety settings.

        Returns:
            str: The text content generated by Gemini.
                 Returns an error message string if generation fails.
        """
        print(f"GeminiClient: Generating content for prompt (first 70 chars): '{prompt[:70]}...'")
        
        # Placeholder for actual Gemini SDK call
        try:
            # response = self.model.generate_content(
            #     prompt,
            #     generation_config=generation_config,
            #     safety_settings=safety_settings
            # )
            # return response.text # Or response.parts[0].text, depending on API version and response structure
            
            # Mock response for now
            if "Translate faithfully" in prompt:
                return f"Mock translation of: {prompt.split(':')[-1].strip()}"
            elif "Critique this" in prompt:
                return f"Mock critique for: {prompt.split(':')[-1].strip()}"
            elif "Revise this" in prompt:
                return f"Mock revised translation for: {prompt.split(':')[-1].strip()}"
            elif "Extract key terms" in prompt:
                 return '{"mock_term_gemini": "Definition from GeminiClient"}' # JSON string
            elif "Summarize" in prompt: # This condition is also met by the summary/terminology prompt
                 # To be more specific for summary/terminology combined prompt:
                 if "Extract key terms" in prompt and "Summarize the main topic" in prompt : # A bit more specific
                     return json.dumps({
                         "theme": "Mocked theme from GeminiClient for combined prompt.",
                         "terms": [{"src": "combined_term", "tgt": "termino_combinado", "note": "Nota combinada"}]
                     })
                 return "Mocked summary-only response from GeminiClient." # Fallback for just "Summarize"
            elif "Split the given subtitle text" in prompt: # For meaning-based splitting
                return json.dumps({
                    "analysis": "Mock analysis for splitting from GeminiClient.",
                    "split_parts": ["Mock part 1 from GeminiClient", "Mock part 2 from GeminiClient"]
                })

            return f"Mocked generic Gemini response to: {prompt[:50]}"

        except Exception as e:
            print(f"GeminiClient: Error during content generation: {e}")
            # In a real scenario, might raise the exception or return a more structured error
            return f"Error: Could not generate content. {e}"

# Example of other potential common utilities:
def some_reusable_decorator(func):
    def wrapper(*args, **kwargs):
        print(f"Decorator: Calling {func.__name__}")
        result = func(*args, **kwargs)
        print(f"Decorator: Finished {func.__name__}")
        return result
    return wrapper

@some_reusable_decorator
def example_utility_function(text: str):
    print(f"Example utility processing: {text}")
    return text.upper()


if __name__ == '__main__':
    print("\nTesting common_utils.py...")

    # Test GeminiClient
    print("\n--- Testing GeminiClient ---")
    mock_api_key = "TEST_API_KEY" # In real use, this would come from config
    gemini_config = {"model_name": "gemini-1.5-flash"} # Example
    
    try:
        client = GeminiClient(api_key=mock_api_key, client_config=gemini_config)
        
        test_prompt_translate = "Translate faithfully from en to es: Hello world"
        translation = client.generate_content(test_prompt_translate)
        print(f"Test Translation: {translation}")

        test_prompt_critique = "Critique this es translation of 'Hello world': Hola mundo"
        critique = client.generate_content(test_prompt_critique)
        print(f"Test Critique: {critique}")

        test_prompt_summarize = "Summarize this text: AI is transforming industries." # Will hit the combined or summary-only
        summary_response = client.generate_content(test_prompt_summarize)
        print(f"Test Summary Response: {summary_response}")

        test_prompt_split = "## Role\nYou are a professional Netflix subtitle splitter...\nSplit the given subtitle text into 2 parts...\n<split_this_sentence>\nThis is a test sentence for splitting.\n</split_this_sentence>"
        split_response = client.generate_content(test_prompt_split)
        print(f"Test Split Response: {split_response}")

        test_prompt_combined_sum_terms = "## Role\nYou are a video translation expert...\nSummarize the main topic...Extract key terms...\n<text>\nSome video content here.\n</text>"
        combined_response = client.generate_content(test_prompt_combined_sum_terms)
        print(f"Test Combined Summary/Terms Response: {combined_response}")

    except ValueError as ve:
        print(f"Error initializing GeminiClient: {ve}")
    except Exception as e:
        print(f"An unexpected error occurred with GeminiClient: {e}")

    # Test other utilities
    print("\n--- Testing other utilities ---")
    processed_text = example_utility_function("test text for utility")
    print(f"Processed by utility: {processed_text}")